version: '3.2'
services:
  neo4j:
    image: neo4j:4.2.5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment: 
      NEO4J_AUTH: neo4j/admin
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4JLABS_PLUGINS: "['graph-data-science', 'apoc']"
      NEO4J_dbms_security_procedures_whitelist: gds.*, apoc.*
      NEO4J_dbms_security_procedures_unrestricted: gds.*, apoc.*
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
            

  db:
    container_name: db-backend-wallet
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456qw
    ports:
      - "3306:3306"
    volumes:
      - ../.volumes/mysql-local-login:/var/lib/mysql
